DrogueriaWeb1/Models/EmpleadosModel.cs
using System.ComponentModel.DataAnnotations;

namespace DrogueriaWeb1.Models
{
    public class EmpleadosModel
    { 
        [Required (ErrorMessage ="El ID del empleado es obligatorio")]
        public string? Id_empleado { get; set; }
        [Required(ErrorMessage = "El Nombre del empleado es obligatorio")]
        public string? Nombre { get; set; }
        public string? Telefono { get;set; }
        


    }
}

DrogueriaWeb1/Models/ErrorViewModel.cs
namespace DrogueriaWeb1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DrogueriaWeb1/Controllers/HomeController.cs
using DrogueriaWeb1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DrogueriaWeb1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DrogueriaWeb1/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using DrogueriaWeb1.Datos;
using DrogueriaWeb1.Models;

namespace DrogueriaWeb1.Controllers
{
    public class MantenedorController : Controller
    {
        EmpleadosDatos _EmpleadosDatos = new EmpleadosDatos();
        
        public IActionResult Listar()
        {
                      
            //Listar todos los empleados
            var oLista = _EmpleadosDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Devuelve vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(EmpleadosModel oEmpleado)
        {
            //Recibe un objeto y lo guarda en la BD
            if (!ModelState.IsValid)
                return View();

            var respuesta = _EmpleadosDatos.Guardar(oEmpleado);

            if (respuesta)
                return RedirectToAction("Listar");
            else 
                return View();
        }
    }
}

DrogueriaWeb1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DrogueriaWeb1/Views/Mantenedor/Guardar.cshtml
@model EmpleadosModel;
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Empleado
    </div>
    <div class="card-body">
        
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="form-group">
                <label class="form-label">ID Empleado</label>
                <input asp-for="Id_empleado" type="text" class="form-control" />
                <span asp-validation-for="Id_empleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control" />
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>



    </div>
</div>

DrogueriaWeb1/Views/Mantenedor/Listar.cshtml
@model List<EmpleadosModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista de Empleados
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">Crear nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Teléfono</th>
            </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id_empleado</td>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td></td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

DrogueriaWeb1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrogueriaWeb1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrogueriaWeb1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DrogueriaWeb1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DrogueriaWeb1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>